### ISSUE TITLE
Recipe: Gourmet Mushroom Soup

### ISSUE THREAD

**Issue by breadsmyth** [deadbody13/deadbody13.github.io#5]
![20231015_161146](https://github.com/deadbody13/deadbody13.github.io/assets/137858575/700349e8-ffc2-4fc6-96ad-2c87d3f8b4c1)
Ingredients:

1/2 stick butter
1/2 tsp truffle oil, plus more for garnish
1 large onion, diced
1 lb cremini or white mushrooms, sliced
2 cups chicken or vegetable stock
1/2 cup dry white wine
2 tsp paprika
1 tsp worcestershire sauce
1 tsp salt, plus more to taste
1 cup heavy cream
1 1/2 Tbsp cornstarch
juice of 1/2 lemon

Directions:

1. Melt butter in a large stockpot. Add truffle oil, onions, and mushrooms. Cook until mushrooms are nicely browned, about 8 minutes. (If the ingredients crowd the pot, work in batches.)
2. Add chicken stock, wine, paprika, worcestershire, salt, and any herbs, vegetables, or spices you want to add. Bring to a boil, then simmer on low heat for about 10 minutes or until slightly reduced.
3. Meanwhile, in a small bowl, combine heavy cream and cornstarch and whisk thoroughly. Stir the cream mixture into the soup and return it to a simmer. Continue simmering until the soup is as thick as you like, about 10 minutes more. 
4. Turn off the heat and stir lemon juice into soup. Season with salt to taste. Serve into bowls, and garnish each bowl with a light touch of truffle oil. 

Notes:

1. I like to dice my mushrooms but keep some of them sliced, for variation in texture.
2. Like all soups, the greatest thing about this recipe is you can add any herbs, vegetables, and spices that you want! Use up your extra ingredients that are about to go bad, or just add all your favorites! Some suggestions that would go great in this recipe include dill, thyme, oregano, parsley, celery, leeks, garlic, and mustard - but you can really use whatever you want! I substituted half the salt in this recipe for a "Wild Mushroom" seasoning blend that I had, and it was amazing.
3. I made this soup with a dry red wine instead of white, and it was still delicious.

**Comment by deadbody13** [comment]
[Post added](https://testing.mostlyharmless.cafe/posts/gourmet-mushroom-soup.html).

You're now in the first post to feature an image.

**Comment by deadbody13** [comment]
Recipe submitted
